const cropsData = [
  { crop_id: 101, crop_name_en: 'Potato', crop_name_bn: 'আলু', crop_image: '/src/images/potato-1694096.jpg' },
  { crop_id: 102, crop_name_en: 'Carrots', crop_name_bn: 'গাজর', crop_image: '/src/images/carrots-2387394.jpg' },
  { crop_id: 103, crop_name_en: 'Cucumber', crop_name_bn: 'শসা', crop_image: '/src/images/Cucumber.jpg' },
  { crop_id: 104, crop_name_en: 'Ladies finger', crop_name_bn: 'ঢেঁড়স', crop_image: '/src/images/lady-finger-6548609.jpg' },
  { crop_id: 105, crop_name_en: 'Brinjal', crop_name_bn: 'বেগুন', crop_image: '/src/images/Bringal.jpg' },
  { crop_id: 106, crop_name_en: 'Peas', crop_name_bn: 'মটরশুটি', crop_image: '/src/images/peas.jpg' },
  { crop_id: 107, crop_name_en: 'Radish', crop_name_bn: 'মূলা', crop_image: '/src/images/radish-3151347.jpg' },
  { crop_id: 108, crop_name_en: 'String beans', crop_name_bn: 'বরবটি', crop_image: '/src/images/String beans.jpg' },
  { crop_id: 109, crop_name_en: 'Bitter gourd', crop_name_bn: 'করলা', crop_image: '/src/images/Bitter gourd.jpg' },
  { crop_id: 110, crop_name_en: 'Cabbage', crop_name_bn: 'বাঁধাকপি', crop_image: '/src/images/cabbage-1663179.jpg' },
  { crop_id: 111, crop_name_en: 'Water amaranth', crop_name_bn: 'কলমি শাক', crop_image: '/src/images/Water amaranth.jpg' },
  { crop_id: 112, crop_name_en: 'Spinach', crop_name_bn: 'পালং শাক', crop_image: '/src/images/Spinach.jpg' },
  { crop_id: 113, crop_name_en: 'Red Leafy', crop_name_bn: 'লাল শাক', crop_image: '/src/images/Red Leafy.jpg' },
  { crop_id: 114, crop_name_en: 'Pumpkin', crop_name_bn: 'কুমড়া', crop_image: '/src/images/pumpkins-6641324.jpg' },
  { crop_id: 115, crop_name_en: 'Corn', crop_name_bn: 'ভুট্টা', crop_image: '/src/images/Corn.jpeg' },
  { crop_id: 116, crop_name_en: 'Onion', crop_name_bn: 'পেঁয়াজ', crop_image: '/src/images/onions-1397037.jpg' },
  { crop_id: 117, crop_name_en: 'Capsicum', crop_name_bn: 'ক্যাপসিকাম', crop_image: '/src/images/Capsicum.jpg' },
  { crop_id: 118, crop_name_en: 'Chili', crop_name_bn: 'মরিচ', crop_image: '/src/images/Chili.jpg' },
  { crop_id: 119, crop_name_en: 'Kohlrabi', crop_name_bn: 'ওলকপি', crop_image: '/src/images/kohlrabi-74276_1280.jpg' },
  { crop_id: 120, crop_name_en: 'Garlic', crop_name_bn: 'রসুন', crop_image: '/src/images/garlic-5207282.jpg' },
  { crop_id: 121, crop_name_en: 'Ginger', crop_name_bn: 'আদা', crop_image: '/src/images/ginger-5108742.jpg' },
  { crop_id: 122, crop_name_en: 'Basil', crop_name_bn: 'পুদিনা', crop_image: '/src/images/Basil.jpg' },
  { crop_id: 123, crop_name_en: 'Arum', crop_name_bn: 'ওলকচু', crop_image: '/src/images/Arum.jpeg' },
  { crop_id: 124, crop_name_en: 'Palwal', crop_name_bn: 'পটল', crop_image: '/src/images/palwal.jpeg' },
  { crop_id: 125, crop_name_en: 'Drumstick', crop_name_bn: 'সজনে', crop_image: '/src/images/Drumstick.jpg' },
  { crop_id: 126, crop_name_en: 'Bottle gourd', crop_name_bn: 'লাউ', crop_image: '/src/images/Bottle gourd.jpeg' },
  { crop_id: 127, crop_name_en: 'Sweet potato', crop_name_bn: 'মিষ্টি আলু', crop_image: '/src/images/sweet-potato-1666707.jpg' },
  { crop_id: 128, crop_name_en: 'Sweet bitter gourd', crop_name_bn: 'কাঁকরোল', crop_image: '/src/images/Sweet bitter gourd.jpg' },
  { crop_id: 129, crop_name_en: 'Mint Leaves', crop_name_bn: 'পুদিনা পাতা', crop_image: '/src/images/Mint Leaves.jpg' },
  { crop_id: 130, crop_name_en: 'Colocasia leaves', crop_name_bn: 'কচু পাতা', crop_image: '/src/images/Colocasia leaves.jpeg' },
  { crop_id: 131, crop_name_en: 'Ridge Gourd', crop_name_bn: 'ঝিঙ্গা', crop_image: '/src/images/Ridge Gourd.jpeg' },
  { crop_id: 132, crop_name_en: 'Coriander leaves', crop_name_bn: 'ধনিয়া পাতা', crop_image: '/src/images/coriander.jpg' },
  { crop_id: 133, crop_name_en: 'Papaya', crop_name_bn: 'পেঁপে', crop_image: '/src/images/papaya-3652074.jpg' },
  { crop_id: 134, crop_name_en: 'Bean', crop_name_bn: 'শিম', crop_image: '/src/images/Bean.jpg' },
  { crop_id: 135, crop_name_en: 'Cauliflower', crop_name_bn: 'ফুলকপি', crop_image: '/src/images/cauliflower-4147118.jpg' },
  { crop_id: 136, crop_name_en: 'Tomatoes', crop_name_bn: 'টমেটো', crop_image: '/src/images/tomatoes-4348557.jpg' },
  { crop_id: 137, crop_name_en: 'Zucchini', crop_name_bn: 'ধুন্দুল', crop_image: '/src/images/zucchini-8346555.jpg' },
  { crop_id: 138, crop_name_en: 'Snake gourd', crop_name_bn: 'চিচিঙ্গা', crop_image: '/src/images/snake gourd.jpg' },
  { crop_id: 139, crop_name_en: 'Broccoli', crop_name_bn: 'ব্রোকলি', crop_image: '/src/images/broccoli.jpg' },
  { crop_id: 140, crop_name_en: 'Bananas', crop_name_bn: 'কলা', crop_image: '/src/images/banana-2449019.jpg' },
  { crop_id: 141, crop_name_en: 'Jackfruit', crop_name_bn: 'কাঁঠাল', crop_image: '/src/images/jackfruit22.jpeg' },
  { crop_id: 142, crop_name_en: 'Mango', crop_name_bn: 'আম', crop_image: '/src/images/Mango.jpg' },
  { crop_id: 143, crop_name_en: 'Guava', crop_name_bn: 'পেয়ারা', crop_image: '/src/images/guava-188440.jpg' },
  { crop_id: 144, crop_name_en: 'Lemon', crop_name_bn: 'লেবু', crop_image: '/src/images/Lemon.jpeg' },
  { crop_id: 145, crop_name_en: 'Hog plum', crop_name_bn: 'আমড়া', crop_image: '/src/images/Hog plum.jpg' },
  { crop_id: 146, crop_name_en: 'Olive', crop_name_bn: 'জলপাই', crop_image: '/src/images/Olive.jpeg' },
  { crop_id: 147, crop_name_en: 'Dates', crop_name_bn: 'খেজুর', crop_image: '/src/images/Dates.jpg' },
  { crop_id: 148, crop_name_en: 'Coconut', crop_name_bn: 'নারিকেল', crop_image: '/src/images/coconut-tree-5288844.jpg' },
  { crop_id: 149, crop_name_en: 'Gooseberry', crop_name_bn: 'আমলকী', crop_image: '/src/images/Gooseberry.jpg' },
  { crop_id: 150, crop_name_en: 'Palm', crop_name_bn: 'তাল', crop_image: '/src/images/Palm.jpg' },
  { crop_id: 151, crop_name_en: 'Sweet Orange', crop_name_bn: 'কমলা', crop_image: '/src/images/Sweet orange.jpg' },
  { crop_id: 152, crop_name_en: 'Java Apple', crop_name_bn: 'জামরুল', crop_image: '/src/images/java-apple4.png' },
  { crop_id: 153, crop_name_en: 'Wood Apple', crop_name_bn: 'বেল', crop_image: '/src/images/Wood Apple.jpg' },
  { crop_id: 154, crop_name_en: 'Elephant Wood Apple', crop_name_bn: 'কদবেল', crop_image: '/src/images/Elephant Wood Apple.jpg' },
  { crop_id: 155, crop_name_en: 'Sapodilla', crop_name_bn: 'সফেদা', crop_image: '/src/images/sapodilla-6834191.jpg' },
  { crop_id: 156, crop_name_en: 'Wheat', crop_name_bn: 'গম', crop_image: '/src/images/wheat-3524861.jpg' },
  { crop_id: 157, crop_name_en: 'Lentils', crop_name_bn: 'মসুর ডাল', crop_image: '/src/images/lentils-4160220.jpg' },
  { crop_id: 158, crop_name_en: 'Chickpea', crop_name_bn: 'ছোলার ডাল', crop_image: '/src/images/chickpeas-3663027.jpg' },
  { crop_id: 159, crop_name_en: 'Groundnut', crop_name_bn: 'বাদাম', crop_image: '/src/images/groundnut.jpg' },
  { crop_id: 160, crop_name_en: 'Mustard', crop_name_bn: 'সরিষা', crop_image: '/src/images/mustard.jpg' },
  { crop_id: 161, crop_name_en: 'Mung bean', crop_name_bn: 'মুগ', crop_image: '/src/images/Mung bean.jpg' },
  { crop_id: 162, crop_name_en: 'Jute', crop_name_bn: 'পাট', crop_image: '/src/images/jute.jpg' },
  { crop_id: 163, crop_name_en: 'Aus Rice', crop_name_bn: 'আউস ধান', crop_image: '/src/images/aus.jpg' },
  { crop_id: 164, crop_name_en: 'Aman Rice', crop_name_bn: 'আমন ধান', crop_image: '/src/images/aman.jpg' },
  { crop_id: 165, crop_name_en: 'Boro Rice', crop_name_bn: 'বোরো ধান', crop_image: '/src/images/boro.jpg' },
  { crop_id: 166, crop_name_en: 'Lychee', crop_name_bn: 'লিচু', crop_image: '/src/images/lychee-5368365.jpg' },
  { crop_id: 167, crop_name_en: 'Watermelon', crop_name_bn: 'তরমুজ', crop_image: '/src/images/watermelon.png' },
  { crop_id: 168, crop_name_en: 'Betel leaf', crop_name_bn: 'পান', crop_image: '/src/images/betel leaf.jpeg' },
  { crop_id: 169, crop_name_en: 'Sugarcane', crop_name_bn: 'আখ', crop_image: '/src/images/sugarcane.jpg' },
  { crop_id: 170, crop_name_en: 'Betel nut', crop_name_bn: 'সুপারি', crop_image: '/src/images/betel nut.jpg' }
];

export default cropsData;
