const cropsData = [
    { crop_id: 101, crop_name: 'Potato', crop_image: '/src/images/potato-1694096.jpg' },
    { crop_id: 102, crop_name: 'Carrots', crop_image: '/src/images/carrots-2387394.jpg' },
    { crop_id: 103, crop_name: 'Cucumber', crop_image: '/src/images/Cucumber.jpg' },
    { crop_id: 104, crop_name: 'Ladies finger', crop_image: '/src/images/lady-finger-6548609.jpg' },
    { crop_id: 105, crop_name: 'Brinjal', crop_image: '/src/images/Bringal.jpg' },
    { crop_id: 106, crop_name: 'Peas', crop_image: '/src/images/peas.jpg' },
    { crop_id: 107, crop_name: 'Radish', crop_image: '/src/images/radish-3151347.jpg' },
    { crop_id: 108, crop_name: 'String beans', crop_image: '/src/images/String beans.jpg' },
    { crop_id: 109, crop_name: 'Bitter gourd', crop_image: '/src/images/Bitter gourd.jpg' },
    { crop_id: 110, crop_name: 'Cabbage', crop_image: '/src/images/cabbage-1663179.jpg' },
    { crop_id: 111, crop_name: 'Water amaranth', crop_image: '/src/images/Water amaranth.jpg' },
    { crop_id: 112, crop_name: 'Spinach', crop_image: '/src/images/Spinach.jpg' },
    { crop_id: 113, crop_name: 'Red Leafy', crop_image: '/src/images/Red Leafy.jpg' },
    { crop_id: 114, crop_name: 'Pumpkin', crop_image: '/src/images/pumpkins-6641324.jpg' },
    { crop_id: 115, crop_name: 'Corn', crop_image: '/src/images/Corn.jpeg' },
    { crop_id: 116, crop_name: 'Onion', crop_image: '/src/images/onions-1397037.jpg' },
    { crop_id: 117, crop_name: 'Capsicum', crop_image: '/src/images/Capsicum.jpg' },
    { crop_id: 118, crop_name: 'Chili', crop_image: '/src/images/Chili.jpg' },
    { crop_id: 119, crop_name: 'Kohlrabi', crop_image: '/src/images/kohlrabi-74276_1280.jpg' },
    { crop_id: 120, crop_name: 'Garlic', crop_image: '/src/images/garlic-5207282.jpg' },
    { crop_id: 121, crop_name: 'Ginger', crop_image: '/src/images/ginger-5108742.jpg' },
    { crop_id: 122, crop_name: 'Basil', crop_image: '/src/images/Basil.jpg' },
    { crop_id: 123, crop_name: 'Arum', crop_image: '/src/images/Arum.jpeg' },
    { crop_id: 124, crop_name: 'Palwal', crop_image: '/src/images/palwal.jpeg' },
    { crop_id: 125, crop_name: 'Drumstick', crop_image: '/src/images/Drumstick.jpg' },
    { crop_id: 126, crop_name: 'Bottle gourd', crop_image: '/src/images/Bottle gourd.jpeg' },
    { crop_id: 127, crop_name: 'Sweet potato', crop_image: '/src/images/sweet-potato-1666707.jpg' },
    { crop_id: 128, crop_name: 'Sweet bitter gourd', crop_image: '/src/images/Sweet bitter gourd.jpg' },
    { crop_id: 129, crop_name: 'Mint Leaves', crop_image: '/src/images/Mint Leaves.jpg' },
    { crop_id: 130, crop_name: 'Colocasia leaves', crop_image: '/src/images/Colocasia leaves.jpeg' },
    { crop_id: 131, crop_name: 'Ridge Gourd', crop_image: '/src/images/Ridge Gourd.jpeg' },
    { crop_id: 132, crop_name: 'Coriander leaves', crop_image: '/src/images/coriander.jpg' },
    { crop_id: 133, crop_name: 'Papaya', crop_image: '/src/images/papaya-3652074.jpg' },
    { crop_id: 134, crop_name: 'Bean', crop_image: '/src/images/Bean.jpg' },
    { crop_id: 135, crop_name: 'Cauliflower', crop_image: '/src/images/cauliflower-4147118.jpg' },
    { crop_id: 136, crop_name: 'Tomatoes', crop_image: '/src/images/tomatoes-4348557.jpg' },
    { crop_id: 137, crop_name: 'Zucchini', crop_image: '/src/images/zucchini-8346555.jpg' },
    { crop_id: 138, crop_name: 'Snake gourd', crop_image: '/src/images/snake gourd.jpg' },
    { crop_id: 139, crop_name: 'Broccoli', crop_image: '/src/images/broccoli.jpg' },
    { crop_id: 140, crop_name: 'Bananas', crop_image: '/src/images/banana-2449019.jpg' },
    { crop_id: 141, crop_name: 'Jackfruit', crop_image: '/src/images/jackfruit22.jpeg' },
    { crop_id: 142, crop_name: 'Mango', crop_image: '/src/images/Mango.jpg' },
    { crop_id: 143, crop_name: 'Guava', crop_image: '/src/images/guava-188440.jpg' },
    { crop_id: 144, crop_name: 'Lemon', crop_image: '/src/images/Lemon.jpeg' },
    { crop_id: 145, crop_name: 'Hog plum', crop_image: '/src/images/Hog plum.jpg' },
    { crop_id: 146, crop_name: 'Olive', crop_image: '/src/images/Olive.jpeg' },
    { crop_id: 147, crop_name: 'Dates', crop_image: '/src/images/Dates.jpg' },
    { crop_id: 148, crop_name: 'Coconut', crop_image: '/src/images/coconut-tree-5288844.jpg' },
    { crop_id: 149, crop_name: 'Gooseberry', crop_image: '/src/images/Gooseberry.jpg' },
    { crop_id: 150, crop_name: 'Palm', crop_image: '/src/images/Palm.jpg' },
    { crop_id: 151, crop_name: 'Sweet Orange', crop_image: '/src/images/Sweet orange.jpg' },
    { crop_id: 152, crop_name: 'Java Apple', crop_image: '/src/images/java-apple4.png' },
    { crop_id: 153, crop_name: 'Wood Apple', crop_image: '/src/images/Wood Apple.jpg' },
    { crop_id: 154, crop_name: 'Elephant Wood Apple', crop_image: '/src/images/Elephant Wood Apple.jpg' },
    { crop_id: 155, crop_name: 'Sapodilla', crop_image: '/src/images/sapodilla-6834191.jpg' },
    { crop_id: 156, crop_name: 'Wheat', crop_image: '/src/images/wheat-3524861.jpg' },
    { crop_id: 157, crop_name: 'Lentils', crop_image: '/src/images/lentils-4160220.jpg' },
    { crop_id: 158, crop_name: 'Chickpea', crop_image: '/src/images/chickpeas-3663027.jpg' },
    { crop_id: 159, crop_name: 'Groundnut', crop_image: '/src/images/groundnut.jpg' },
    { crop_id: 160, crop_name: 'Mustard', crop_image: '/src/images/mustard.jpg' },
    { crop_id: 161, crop_name: 'Mung bean', crop_image: '/src/images/Mung bean.jpg' },
    { crop_id: 162, crop_name: 'Jute', crop_image: '/src/images/jute.jpg' },
    { crop_id: 163, crop_name: 'Aus Rice', crop_image: '/src/images/aus.jpg' },
    { crop_id: 164, crop_name: 'Aman Rice', crop_image: '/src/images/aman.jpg' },
    { crop_id: 165, crop_name: 'Boro Rice', crop_image: '/src/images/boro.jpg' },
    { crop_id: 166, crop_name: 'Lychee', crop_image: '/src/images/lychee-5368365.jpg' },
  ];
  
  export default cropsData;
  
  